[question1]
question = "Which of the following datasets allow duplicates?"
options = ["A. List", "B. Set", "C. Dict"]
answer = "A"

[question2]
question= "What is the first step of a recursion function?"
options = ["A. Recursion case", "B. Call itself", "C. Base case"]
answer = "C"

[question3]
question = "Which programming language is known for having simple syntax"
options = ["A. C++", "B. Python", "C. Java"]
answer = "B"

[question4]
question = "Which programming language has is best for OOP and enterprise-level apps?"
options = ["A. Java", "B. Javascript", "C. Python"]
answer = "A"